return {
  "williamboman/mason.nvim",
  keys = {
    { "<leader>cm", false },
  },
  opts = {
    ensure_installed = {
      "bashls",
      "clangd",
      "cmake",
      "html",
      "cssls",
      "vuels",
      "eslint",
      "glint",
      "ts_ls",
      "vtsls",
      "gopls",
      "jsonls",
      "rust_analyzer",
      "java_language_server",
      "kotlin_language_server",
      "sqls",
      "pyright",
      "pylsp",
      "ruby_lsp",
      "phpactor",
      "lua_ls",
      "groovyls",
      "ltex",
      "markdown_oxide",
      "matlab_ls",
    },
  },
}
